# Generated by Django 2.2.12 on 2022-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='starts',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('FREE', 'free'), ('NOT FREE', 'not free')], default='FREE', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VORCANOES', 'vorcanoes'), ('HOTEL', 'hotel'), ('HILLS', 'hills')], default='VORCANOES', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('RWANDA', 'rwanda'), ('Uganda', 'uganda'), ('BURUNDI', 'burundi'), ('CONGO', 'congo')], default='RWANDA', max_length=25),
        ),
    ]
